name: Build & Push Docker Image CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  backend:
    runs-on: ubuntu-latest
    if: ${{github.event.review.state == 'approved' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}

    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_HUB_USERNAME }}
          password: ${{ DOCKER_HUB_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t bobapp-back .
          docker tag bobapp-back ${{ DOCKER_HUB_USERNAME }}/bobapp-back:latest
          docker push ${{ DOCKER_HUB_USERNAME }}/bobapp-back:latest

  frontend:
    runs-on: ubuntu-latest
    if: ${{github.event.review.state == 'approved' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}

    defaults:
      run:
        working-directory: ${{ github.workspace }}/front

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_HUB_USERNAME }}
          password: ${{ DOCKER_HUB_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t bobapp-front .
          docker tag bobapp-front ${{ DOCKER_HUB_USERNAME }}/bobapp-front:latest
          docker push ${{ DOCKER_HUB_USERNAME }}/bobapp-front:latest
